// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserNameAPI;

namespace UserNameAPI.Migrations
{
    [DbContext(typeof(UserNameDbContext))]
    partial class UserNameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserNameLibrary.UserName", b =>
                {
                    b.Property<int>("NameId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Service");

                    b.Property<DateTime>("created");

                    b.Property<DateTime>("modified");

                    b.HasKey("NameId");

                    b.ToTable("UserNames");

                    b.HasData(
                        new
                        {
                            NameId = 1,
                            Email = "myladys21111@live.com",
                            Password = "moonlIte00",
                            Service = "Outlook.com",
                            created = new DateTime(2020, 6, 2, 1, 19, 12, 317, DateTimeKind.Utc).AddTicks(9560),
                            modified = new DateTime(2020, 6, 2, 1, 19, 12, 317, DateTimeKind.Utc).AddTicks(9561)
                        },
                        new
                        {
                            NameId = 2,
                            Email = "ltdtwo@outlook.com",
                            Password = "moonlIte00",
                            Service = "Outlook.com",
                            created = new DateTime(2020, 6, 2, 1, 19, 12, 318, DateTimeKind.Utc).AddTicks(692),
                            modified = new DateTime(2020, 6, 2, 1, 19, 12, 318, DateTimeKind.Utc).AddTicks(692)
                        },
                        new
                        {
                            NameId = 3,
                            Email = "wavetravel@outlook.com",
                            Password = "moonlIte00",
                            Service = "Outlook.com",
                            created = new DateTime(2020, 6, 2, 1, 19, 12, 318, DateTimeKind.Utc).AddTicks(704),
                            modified = new DateTime(2020, 6, 2, 1, 19, 12, 318, DateTimeKind.Utc).AddTicks(704)
                        },
                        new
                        {
                            NameId = 4,
                            Email = "myladys21111@gmail.com",
                            Password = "moonlIte00",
                            Service = "Gmail",
                            created = new DateTime(2020, 6, 2, 1, 19, 12, 318, DateTimeKind.Utc).AddTicks(705),
                            modified = new DateTime(2020, 6, 2, 1, 19, 12, 318, DateTimeKind.Utc).AddTicks(705)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
